FROM arm32v6/python:3.6-alpine3.7

WORKDIR /var/app

ARG PYTHON_REQUIREMENTS=./requirements/production.txt
COPY ./requirements/ ./requirements

RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add postgresql-dev make \
    && pip install --use-wheel --no-cache-dir -r ${PYTHON_REQUIREMENTS} \
    && apk del build-deps

COPY . .

EXPOSE 8000

CMD ["./run.sh"]
