version: "3.1"
services:
  web:
    build:
      context: .
      args:
        PYTHON_REQUIREMENTS: ./requirements/development.txt
    command: make dev
    ports:
      - "8061:8000"
    links:
      - db
    environment:
      - ENVIRONMENT=dev
      - DB_HOST=db
      - DB_USER=mind
      - DB_PASSWORD=mind
      - DB_DATABASE=mind
      - FLASK_APP=application.py
      - FLASK_DEBUG=1
      - GOOGLE_ID=
      - GOOGLE_SECRET=
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=mind
      - POSTGRES_PASSWORD=mind
      - POSTGRES_DB=mind
